export const services =  {
    categories: ['All', 'Daycare', 'Grooming', 'Add on'],
    packages: [
        { id: 1, image: '/assets/img/SAMPLE.jpg', title: 'BATH & HAIR CUT PACKAGE', category: 'Grooming', description: 'A description of our service...', cost: 9000 },
        { id: 2, image: '/assets/img/SAMPLE.jpg', title: 'BATH & BRUSH PACKAGE', category: 'Grooming', description: 'A description of our service...', cost: 15000 },
        { id: 3, image: '/assets/img/SAMPLE.jpg', title: 'TOP DOG PACKAGE', category: 'Grooming', description: 'A description of our service...', cost: 5000 },
        { id: 4, image: '/assets/img/SAMPLE.jpg', title: 'Pricing', category: 'Daycare', description: 'A description of our service...', cost: 8000 },
        { id: 5, image: '/assets/img/SAMPLE.jpg', title: 'With Grooming', category: 'Daycare', description: 'A description of our service...', cost: 7500 },
        { id: 6, image: '/assets/img/SAMPLE.jpg', title: 'Packages', category: 'Daycare', description: 'A description of our service...', cost: 9000 },
        { id: 7, image: '/assets/img/SAMPLE.jpg', title: 'Flea & Tick Shampoo', category: 'Add on', description: 'A description of our service...', cost: 8000 },
        { id: 8, image: '/assets/img/SAMPLE.jpg', title: 'De-matting', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 9, image: '/assets/img/SAMPLE.jpg', title: 'De-shedding', category: 'Add on', description: 'A description of our service...', cost: 7000 },
        { id: 10, image: '/assets/img/SAMPLE.jpg', title: 'Hand-stripping', category: 'Add on', description: 'A description of our service...', cost: 4000 },
        { id: 11, image: '/assets/img/SAMPLE.jpg', title: 'Extra Handling Fee', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 12, image: '/assets/img/SAMPLE.jpg', title: 'Designer cut fee', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 13, image: '/assets/img/SAMPLE.jpg', title: 'Hair Dye', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 14, image: '/assets/img/SAMPLE.jpg', title: 'Nail trimming', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 15, image: '/assets/img/SAMPLE.jpg', title: 'Gland Expression', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 16, image: '/assets/img/SAMPLE.jpg', title: 'Teeth Brush', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 17, image: '/assets/img/SAMPLE.jpg', title: 'Ear Cleaning', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 18, image: '/assets/img/SAMPLE.jpg', title: 'Hot, Cold and In Between', category: 'Water', description: 'A description of our service...', cost: 3500 },
        { id: 19, image: '/assets/img/SAMPLE.jpg', title: 'Me Time', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 20, image: '/assets/img/SAMPLE.jpg', title: 'Reflexology', category: 'Ammenities', description: 'A description of our service...', cost: 2000 },
    ],
}