export const services =  {
    categories: ['All', 'Daycare', 'Grooming', 'Add on'],
    packages: [
        { id: 1, image: '/assets/img/Services/service-1.jpg', title: 'BATH & HAIR CUT PACKAGE', category: 'Grooming', description: 'A description of our service...', cost: 9000 },
        { id: 2, image: '/assets/img/Services/service-2.jpg', title: 'BATH & BRUSH PACKAGE', category: 'Grooming', description: 'A description of our service...', cost: 15000 },
        { id: 3, image: '/assets/img/Services/service-3.jpg', title: 'TOP DOG PACKAGE', category: 'Grooming', description: 'A description of our service...', cost: 5000 },
        { id: 4, image: '/assets/img/Services/service-4.jpg', title: 'Pricing', category: 'Daycare', description: 'A description of our service...', cost: 8000 },
        { id: 5, image: '/assets/img/Services/service-5.jpg', title: 'With Grooming', category: 'Daycare', description: 'A description of our service...', cost: 7500 },
        { id: 6, image: '/assets/img/Services/service-6.jpg', title: 'Packages', category: 'Daycare', description: 'A description of our service...', cost: 9000 },
        { id: 7, image: '/assets/img/Services/service-7.jpg', title: 'Flea & Tick Shampoo', category: 'Add on', description: 'A description of our service...', cost: 8000 },
        { id: 8, image: '/assets/img/Services/service-8.jpg', title: 'De-matting', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 9, image: '/assets/img/Services/service-9.jpg', title: 'De-shedding', category: 'Add on', description: 'A description of our service...', cost: 7000 },
        { id: 10, image: '/assets/img/Services/service-10.jpg', title: 'Hand-stripping', category: 'Add on', description: 'A description of our service...', cost: 4000 },
        { id: 11, image: '/assets/img/Services/service-11.jpg', title: 'Extra Handling Fee', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 12, image: '/assets/img/Services/service-12.jpg', title: 'Designer cut fee', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 13, image: '/assets/img/Services/service-13.jpg', title: 'Hair Dye', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 14, image: '/assets/img/Services/service-14.jpg', title: 'Nail trimming', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 15, image: '/assets/img/Services/service-15.jpg', title: 'Gland Expression', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 16, image: '/assets/img/Services/service-16.jpg', title: 'Teeth Brush', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 17, image: '/assets/img/Services/service-17.jpg', title: 'Ear Cleaning', category: 'Add on', description: 'A description of our service...', cost: 9000 },
        { id: 18, image: '/assets/img/Services/service-18.jpg', title: 'Hot, Cold and In Between', category: 'Water', description: 'A description of our service...', cost: 3500 },
        { id: 19, image: '/assets/img/Services/service-19.jpg', title: 'Me Time', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 20, image: '/assets/img/Services/service-20.jpg', title: 'Reflexology', category: 'Ammenities', description: 'A description of our service...', cost: 2000 },
    ],
}